global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: backend
    static_configs:
      - targets: ['api:3000']
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']