global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: traefik
    static_configs:
      - targets: ['traefik:8080']
  - job_name: db
    static_configs:
      - targets: ['db-admin:9216']
  - job_name: loki
    static_configs:
      - targets: ['loki:3100']