version: "3"
services:
  api:
    extends:
      file: ./packages/api/docker-compose.yml
      service: api
  db:
    extends:
      file: ./packages/db/docker-compose.yml
      service: db
  grafana:
    extends:
      file: ./packages/grafana/docker-compose.yml
      service: grafana
  prometheus:
    extends:
      file: ./packages/prometheus/docker-compose.yml
      service: prometheus
  cadvisor:
    extends:
      file: ./packages/cadvisor/docker-compose.yml
      service: cadvisor
networks:
  local:
    driver: bridge

volumes:
  grafana-data:
  mongo-data:
    driver: local
