version: "3"
services:
  api:
    extends:
      file: ./packages/api/docker-compose.yml
      service: api
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - local
    volumes:
      - mongo-data:/data/db
    command:
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
networks:
  local:
    driver: bridge

volumes:
  mongo-data:
    driver: local
