version: "3"
services:
  api:
    extends:
      file: ./packages/api/docker-compose.yml
      service: api
    depends_on:
      - db
  blog:
    extends:
      file: ./packages/blog-mf/docker-compose.yml
      service: blog
    depends_on:
      - db
  db:
    extends:
      file: ./packages/db/docker-compose.yml
      service: db
  db-admin:
    extends:
      file: ./packages/db-admin/docker-compose.yml
      service: db-admin
    depends_on:
      - db
  db-ui:
    extends:
      file: ./packages/db-ui/docker-compose.yml
      service: db-ui
    depends_on:
      - db
  grafana:
    extends:
      file: ./packages/grafana/docker-compose.yml
      service: grafana
    depends_on:
      - prometheus
  prometheus:
    extends:
      file: ./packages/prometheus/docker-compose.yml
      service: prometheus
    depends_on:
      - api
      - cadvisor
  cadvisor:
    extends:
      file: ./packages/cadvisor/docker-compose.yml
      service: cadvisor
  notification-sender-ms:
    extends:
      file: ./packages/notification-sender-ms/docker-compose.yml
      service: notification-sender-ms
    depends_on:
      - rabbitmq
  rabbitmq:
    extends:
      file: ./packages/rabbitmq/docker-compose.yml
      service: rabbitmq
  sonarqube:
    extends:
      file: ./packages/sonarqube/docker-compose.yml
      service: sonarqube
  traefik:
    extends:
      file: ./packages/traefik/docker-compose.yml
      service: traefik
    depends_on:
      - api
      - grafana
      - prometheus
      - cadvisor
  loki:
    extends:
      file: ./packages/loki/docker-compose.yml
      service: loki
    depends_on:
      - api
  promtail:
    extends:
      file: ./packages/promtail/docker-compose.yml
      service: promtail
    depends_on:
      - api

networks:
  local:
    driver: bridge

volumes:
  grafana-data:
  traefik-public-certificates:
  mongo-data:
    driver: local
  data:
