version: "3"
services:
  api:
    extends:
      file: ./packages/api/docker-compose.yml
      service: api
  db:
    extends:
      file: ./packages/db/docker-compose.yml
      service: db
networks:
  local:
    driver: bridge

volumes:
  mongo-data:
    driver: local
