version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    ports: 
      - 3000:3000
    container_name: api
    networks:
      - local
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - local
    volumes:
      - mongo-data:/data/db
networks:
  local:
    driver: bridge

volumes:
  mongo-data:
    driver: local