version: "3"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3001:3001
    environment:
      - GF_SERVER_HTTP_PORT=3001
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/dashboard.json
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards/
      - ./provisioning:/etc/grafana/provisioning
    labels:
      traefik.http.routers.grafana-architecture.rule: Host(`grafana.localhost`)
      traefik.http.services.grafana-architecture.loadbalancer.server.port: 3001
    networks:
      - local
    depends_on:
      - api
