version: "3"
services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3001:3001
    environment:
      - GF_SERVER_HTTP_PORT=3001
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/traefik-2-2_rev1.json
      - GF_SERVER_DOMAIN=localhost
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards/
      - ./plugins:/var/lib/grafana/plugins/
      - ./provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    labels:
      traefik.enable: true
      
      traefik.http.routers.grafana-http.rule: Host(`grafana.${DOMAIN}`)
      traefik.http.routers.grafana-http.entrypoints: http
      traefik.http.routers.grafana-http.middlewares: https-redirect

      traefik.http.routers.grafana-https.rule: Host(`grafana.${DOMAIN}`)
      traefik.http.routers.grafana-https.entrypoints: https
      traefik.http.routers.grafana-https.tls: true

      traefik.http.routers.grafana-https.tls.certresolver: le
      traefik.http.routers.grafana-https.middlewares: admin-auth

      traefik.http.services.grafana-architecture.loadbalancer.server.port: 3001
    networks:
      - local
    restart: always