version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --providers.docker
      - --log.level=INFO
      - --entrypoints.web.address=:80
    labels:
      traefik.http.routers.dash.rule: Host(`dash.localhost`)
    deploy:
      resources:
        limits:
          cpus: "1.50"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 20M
    networks:
      - local
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
