version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --providers.docker
      - --metrics.prometheus=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=sebastienleonce91@gmail.com
      - --certificatesresolvers.le.acme.storage=/etc/letsencrypt/live/architecture.sleonce.dev/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    labels:
      traefik.enable: true

      traefik.docker.network: local

      traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.https-redirect.redirectscheme.permanent: true

      traefik.http.middlewares.admin-auth.basicauth.users: ${ADMIN_USER}:${HASHED_PASSWORD}

      traefik.http.routers.traefik-public-http.rule: Host(`traefik.${DOMAIN}`)
      traefik.http.routers.traefik-public-http.entrypoints: http
      traefik.http.routers.traefik-public-http.middlewares: https-redirect

      traefik.http.routers.traefik-public-https.rule: Host(`traefik.${DOMAIN}`)
      traefik.http.routers.traefik-public-https.entrypoints: https
      traefik.http.routers.traefik-public-https.tls: true

      traefik.http.routers.traefik-public-https.tls.certresolver: le
      traefik.http.routers.traefik-public-https.middlewares: admin-auth

      traefik.http.services.traefik-public.loadbalancer.server.port: 8080
    deploy:
      resources:
        limits:
          cpus: "1.50"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 20M
    networks:
      - local
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-public-certificates:/etc/letsencrypt/live/architecture.sleonce.dev/
    restart: always
