version: "3.2"
configs:
  loki_config:
    file: ./loki-local-config.yaml

services:
  loki:
    image: grafana/loki:v1.3.0
    command: -config.file=/etc/loki/loki-local-config.yaml
    # configs:
      # - source: packages/loki/loki-local-config.yaml
        # target: /etc/loki/loki-local-config.yaml
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3300:3300"
    volumes:
      - ./local_bind_volume_dir:/data/loki