version: "3.2"
services:
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
  #   command: elasticsearch -Des.network.host=0.0.0.0 xpack.security.enabled=false
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"    
  #   volumes:
  #     - data:/usr/share/elasticsearch/data
  # data:
  #   image: cogniteev/echo
  #   command: echo 'Data Container for Elasticsearch'
  #   volumes:
  #     - /Users/nli/tmp/elasticsearch/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
