version: "3"
services:
  api:
    build:
      context: ../../
      dockerfile: packages/api/Dockerfile
      target: ${NODE_ENV}
    environment:
      - DB_URL
      - NODE_ENV
    ports:
      - 3000:3000
    container_name: api
    labels:
      traefik.http.routers.api-architecture.rule: Host(`api.localhost`)
    networks:
      - local
    volumes:
      - ./src:/usr/app/packages/api/src
      - ./test:/usr/app/packages/api/test
    restart: always
