version: "3"
services:
  api:
    build:
      context: ../../
      dockerfile: packages/api/Dockerfile
      target: ${NODE_ENV}
    image: sleonce/api
    environment:
      - DB_URL
      - NODE_ENV
      - DOMAIN
      - MQ_URL
      - MQ_NOTIFICATION_QUEUE
    ports:
      - 3000:3000
    container_name: api
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`api.${DOMAIN}`)
    networks:
      - local
    volumes:
      - ./src:/usr/app/packages/api/src
      - ./test:/usr/app/packages/api/test
    restart: always
