version: "3"
services:
  api:
    build:
      context: ../../
      dockerfile: packages/api/Dockerfile
      target: ${NODE_ENV}
    image: sleonce/api
    environment:
      - DB_URL
      - NODE_ENV
      - API_URL
    ports:
      - 3000:3000
    container_name: api
    labels:
      traefik.enable: true
      traefik.http.routers.api-architecture.rule: PathPrefix(`/blog`)
      traefik.http.middlewares.api-architecture.stripprefix.prefixes: /blog
      traefik.http.routers.api-architecture.middlewares: api-architecture@docker
    networks:
      - local
    volumes:
      - ./src:/usr/app/packages/api/src
      - ./test:/usr/app/packages/api/test
    restart: always
