version: '3'

services:
  db-ui:
    container_name: "db-ui"
    image: sleonce/db-ui
    labels:
      traefik.enable: true
      
      traefik.http.routers.db-ui-http.rule: Host(`db-ui.${DOMAIN}`)
      traefik.http.routers.db-ui-http.entrypoints: http
      traefik.http.routers.db-ui-http.middlewares: https-redirect

      traefik.http.routers.db-ui-https.rule: Host(`db-ui.${DOMAIN}`)
      traefik.http.routers.db-ui-https.entrypoints: https
      traefik.http.routers.db-ui-https.tls: true

      traefik.http.routers.db-ui-https.tls.certresolver: le
      traefik.http.routers.db-ui-https.middlewares: admin-auth
    restart: always
    ports:
      - "4231:4321"
    environment:
      - MONGO_URL=${DB_URL}
    networks:
      - local