version: "3"
services:
  blog:
    build:
      context: ../../
      dockerfile: packages/blog-mf/Dockerfile
      target: ${NODE_ENV}
    image: sleonce/blog
    ports:
      - 3022:3000
    container_name: blog
    labels:
      traefik.enable: true
      
      traefik.http.routers.blog-http.rule: Host(`${DOMAIN}`)
      traefik.http.routers.blog-http.entrypoints: http
      traefik.http.routers.blog-http.middlewares: https-redirect

      traefik.http.routers.blog-https.rule: Host(`${DOMAIN}`)
      traefik.http.routers.blog-https.entrypoints: https
      traefik.http.routers.blog-https.tls: true

      traefik.http.routers.blog-https.tls.certresolver: le
    networks:
      - local
    volumes:
      - ./src:/usr/app/packages/blog-mf/src
      - ./cypress:/usr/app/packages/blog-mf/cypress
    restart: always
