version: "3"
services:
  cadvisor:
    image: "google/cadvisor:latest"
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    labels:
      traefik.http.routers.cadvisor.rule: PathPrefix(`/cadvisor`)
      traefik.http.middlewares.cadvisor.stripprefix.prefixes: /cadvisor
      traefik.http.routers.cadvisor.middlewares: cadvisor@docker
    networks:
      - local
    ports:
      - "8081:8080"
    restart: always
