name: Docker CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-images:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Test
        run: | 
          docker-compose --env-file ./config/.env.test build
          docker-compose --env-file ./config/.env.test run api yarn workspace @architecture/api test
      - name: Build
        run: yarn build
      - name: Push
        run: docker-compose push
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd architecture
            git pull
            yarn start
