name: Docker CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-images:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: yarn build
