name: Docker CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-images:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        run: echo $DOCKER_HUB_PASS | docker login -u $DOCKER_HUB_USER --password-stdin
      - name: Build the stack
        run: yarn build
      - name: Push
        run: docker-compose push
